config/routes.rb
SimpleChatFour::Application.routes.draw do
  root to: 'chats#index'

  post '/chats/send_chat', to: 'chats#send_chat', as: 'send_chat'

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'users' => 'users#create'
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  mount_uploader :image, AvitarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
  end

  def send_chat
    p params
    data = {username: current_user.username,
            avatar: current_user.image.thumb.url,
            chat_text: params[:chat_input]}  
    Pusher.trigger(params[:channel], 'message', data)
    render nothing: true
  end

end

app/controllers/sessions_controller.rb
  class SessionsController < ApplicationController

  def new
    p session
    @user = User.new
  end

  def create
    user = User.find_by_username(params[:username])
    authenticated_user = user.authenticate(params[:password])
    if authenticated_user
      session[:user_id] = authenticated_user.id
      redirect_to root_path
    else
      redirect_to sessions_new_path
    end
  end

  def destroy
    session[:user_id] = nil
    p session
    redirect_to sessions_new_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    #@user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to root_path
    else
      redirect_to sessions_new_path
    end
  end



  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.haml
%h1 Chat home!
- if current_user
  %h4#user-info
    Logged in as #{current_user.username}
    %img{src: current_user.image.thumb.url}
  #chats-container
    #chats
  = form_tag(send_chat_path, id: 'chat-form', remote: true) do
    = select_tag 'channel', options_for_select([['chatroom', 'chatroom'],['902 Broadway', '902broadway'],['Today With Tanay', 'todaywithtanay'],['Studio 2','studio2']])
    = text_field_tag 'chat_input'
    = submit_tag 'Chat!'
- else
  = link_to "Please log in", sessions_new_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SimpleChatFour
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "http://js.pusher.com/2.1/pusher.min.js"
    = csrf_meta_tags
  %body
    - if current_user
      = link_to "Sign Out", logout_path, method: :delete
    :javascript
      pusher = new Pusher("#{Pusher.key}");
    = yield

app/views/users/_new.html.haml
=form_for @user do |f|
  = f.label :username
  = f.text_field :username
  = f.label :image
  = f.text_field :remote_image_url, placeholder: 'jpg, jpeg, gif, or png'
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit 'Sign-Up'